/**
 * Static coordinate mappings bundled from Supabase migration data.
 * Source: supabase/migrations/004_coordinate_mappings.sql (126 mappings)
 * This file is the primary data source. Supabase is optional/supplementary.
 */

import type { CoordinateMapping } from './supabase'

const STATIC_MAPPINGS: CoordinateMapping[] = [
  {
    questionId: 'cosmic-moon',
    values: [24, 34, 14, 23],
    meanings: [
      'In the I Ching, 24 is the hexagram of return',
      'Hexagram 34 represents the surge of great power',
      'Hexagram 14 is called Great Possession, a time of abundance',
      'Hexagram 23 signals a natural stripping away of the old',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'cosmic-element',
    values: [26, 18, 14, 78],
    meanings: [
      'Iron is element 26, the metal of Mars',
      'Water has a molecular mass of 18',
      "Silicon is element 14, the foundation of Earth's crust",
      'Nitrogen makes up 78% of the atmosphere we breathe',
    ],
    source: 'Periodic Table',
  },
  {
    questionId: 'cosmic-celestial',
    values: [19, 18, 17, 99],
    meanings: [
      'The Sun is tarot card XIX, radiance and vitality',
      'The Moon is tarot card XVIII, intuition and cycles',
      'The Star is tarot card XVII, hope after darkness',
      '99 sits at the boundary, the furthest limit before completion',
    ],
    source: 'Tarot Major Arcana',
  },
  {
    questionId: 'cosmic-season-inner',
    values: [11, 30, 33, 29],
    meanings: [
      'In the I Ching, hexagram 11 is Peace, heaven and earth in harmony',
      'Hexagram 30 is Clinging Fire, warmth that sustains',
      'Hexagram 33 is Retreat, strength in stepping back',
      'Hexagram 29 is The Abysmal, navigating deep water',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'cosmic-time',
    values: [90, 18, 27, 36],
    meanings: [
      'The sun rises at roughly 90 degrees azimuth, due east',
      'At noon, the sun sits near 180 degrees, due south',
      'Sunset falls around 270 degrees azimuth, due west',
      'Midnight aligns with 360 degrees, due north',
    ],
    source: 'Astronomy',
  },
  {
    questionId: 'color-draw',
    values: [65, 47, 59, 53],
    meanings: [
      'Red light has a wavelength of 650 nanometers',
      'Blue light has a wavelength of 470 nanometers',
      'Gold light falls at a wavelength of 590 nanometers',
      'Green light has a wavelength of 530 nanometers',
    ],
    source: 'Optics',
  },
  {
    questionId: 'color-warmth',
    values: [27, 65, 40, 50],
    meanings: [
      'Candlelight glows at a warm 2,700 Kelvin',
      'Daylight measures a cool 6,500 Kelvin',
      'Neutral white light sits around 4,000 Kelvin',
      '5,000 Kelvin is the balance point between warm and cool light',
    ],
    source: 'Kelvin',
  },
  {
    questionId: 'color-light',
    values: [90, 30, 10, 55],
    meanings: [
      'Fresh snow reflects about 90% of the light that hits it',
      'Charcoal reflects only 30% of incoming light',
      'Vantablack absorbs nearly everything, reflecting just 10%',
      "A photographer's grey card reflects 55%, the standard midpoint",
    ],
    source: 'Albedo',
  },
  {
    questionId: 'color-mood',
    values: [96, 64, 85, 42],
    meanings: [
      '963 Hz is the Solfeggio frequency linked to the crown of the head',
      '639 Hz is the Solfeggio frequency associated with the heart',
      '852 Hz is the Solfeggio frequency tied to inner vision',
      '417 Hz is the Solfeggio frequency connected to the sacral center',
    ],
    source: 'Solfeggio Hz',
  },
  {
    questionId: 'symbol-shape',
    values: [31, 18, 61, 30],
    meanings: [
      'Pi begins at 3.14, the ratio of every circle',
      "A triangle's angles always sum to 180 degrees",
      'Phi is 1.618, the golden ratio found in spirals and shells',
      'The speed of light is 3.0 times 10 to the 8th meters per second',
    ],
    source: 'Math Constants',
  },
  {
    questionId: 'symbol-direction',
    values: [36, 18, 90, 27],
    meanings: [
      'North sits at 360 degrees on the compass, a full revolution',
      'South lies at 180 degrees, the halfway point on the compass',
      'East is 90 degrees, a right angle from due north',
      'West falls at 270 degrees on the compass',
    ],
    source: 'Compass Degrees',
  },
  {
    questionId: 'symbol-number',
    values: [33, 77, 99, 21],
    meanings: [
      '33 is a master number in numerology, 3 multiplied by 11',
      '77 is a master number, 7 multiplied by 11',
      '99 is a master number, 9 multiplied by 11',
      '21 is The World card in tarot, the completion of a cycle',
    ],
    source: 'Numerology',
  },
  {
    questionId: 'symbol-animal',
    values: [11, 18, 13, 88],
    meanings: [
      'In tarot, 11 is the Ace of Swords, clarity and the element of air',
      'The Moon card is 18, instinct and the pull of the unconscious',
      'Card 13 is Death, the archetype of rebirth and transformation',
      '88 doubles the Strength card, amplified resilience',
    ],
    source: 'Tarot Archetype',
  },
  {
    questionId: 'symbol-object',
    values: [29, 47, 19, 14],
    meanings: [
      'Copper is element 29, a conductor of heat and current',
      'Silver is element 47, prized for its reflective surface',
      "Gold is associated with 19 in the periodic table's cultural history",
      'Silicon is element 14, the mineral basis of stone and sand',
    ],
    source: 'Material Science',
  },
  {
    questionId: 'emotional-weather',
    values: [20, 98, 99, 45],
    meanings: [
      'A barometric pressure of 1020 hPa marks calm, stable weather',
      '980 hPa signals a low-pressure system and approaching storms',
      'At 99% humidity, the air holds nearly all the moisture it can',
      'Wind at 45 mph is strong enough to bend trees and stir the sea',
    ],
    source: 'Meteorology',
  },
  {
    questionId: 'emotional-energy',
    values: [45, 90, 70, 10],
    meanings: [
      'A wave at 45 degrees is rising, building toward its crest',
      'At 90 degrees a wave reaches its peak amplitude',
      '270 degrees marks the falling phase, a wave descending',
      'Zero degrees is a wave at rest, still and unmoving',
    ],
    source: 'Wave Physics',
  },
  {
    questionId: 'emotional-body',
    values: [76, 44, 32, 11],
    meanings: [
      '76 pairs the crown and third eye, the two highest chakras',
      '44 doubles the heart chakra, the center of feeling',
      '32 combines the solar plexus and sacral, seat of instinct',
      '11 pairs the root with itself, primal grounding',
    ],
    source: 'Chakra System',
  },
  {
    questionId: 'emotional-need',
    values: [21, 32, 54, 89],
    meanings: [
      'An octave has a 2:1 ratio, the most fundamental harmony',
      'A perfect fifth is a 3:2 ratio, the backbone of most music',
      'A major third at 5:4 creates the warmth in a chord',
      '89 is a Fibonacci number, each term the sum of the two before',
    ],
    source: 'Music/Fibonacci',
  },
  {
    questionId: 'love-element',
    values: [31, 19, 66, 74],
    meanings: [
      'Gallium is element 31, a metal that melts in your hand',
      'Potassium is element 19, so reactive it ignites in water',
      'Dysprosium is element 66, a rare earth found deep in the crust',
      'Tungsten is element 74, the densest and most enduring metal',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'love-time',
    values: [10, 12, 18, 24],
    meanings: [
      '10:00 is mid-morning, when the day is still becoming',
      '12:00 is noon, the brightest point of the day',
      '18:00 is evening, when daylight turns inward',
      '00:00 is midnight, the threshold between one day and the next',
    ],
    source: 'Clock (24h)',
  },
  {
    questionId: 'love-word',
    values: [52, 85, 63, 46],
    meanings: [
      'The letters in LOVE sum to 54 in ordinal gematria, reduced to 52',
      'The letters in TRUTH sum to 87, reduced to 85',
      'The letters in SORRY sum to 95, reduced to 63',
      'The letters in STAY sum to 65, reduced to 46',
    ],
    source: 'Gematria',
  },
  {
    questionId: 'love-color',
    values: [65, 47, 79, 49],
    meanings: [
      'Red light peaks at 650 nanometers, the longest visible wavelength',
      'Silver is element 47, named for its mirror-like reflection',
      'Gold is element 79, the only naturally yellow metal',
      'Indium is element 49, a soft lustrous metal',
    ],
    source: 'Periodic/Optics',
  },
  {
    questionId: 'love-body',
    values: [72, 40, 27, 20],
    meanings: [
      'The average resting heart beats 72 times per minute',
      'Gamma brainwaves fire at 40 Hz during focused awareness',
      'The human hand contains 27 individual bones',
      '20/20 is the baseline for normal visual clarity',
    ],
    source: 'Biology',
  },
  {
    questionId: 'love-season',
    values: [21, 22, 23, 12],
    meanings: [
      'The spring equinox falls around March 21',
      'The summer solstice falls around June 22',
      'The autumn equinox falls around September 23',
      'December is the 12th month, the depth of winter',
    ],
    source: 'Solstice/Calendar',
  },
  {
    questionId: 'love-distance',
    values: [10, 99, 50, 55],
    meanings: [
      '10% represents close proximity, almost touching',
      '99% is the furthest extent, nearly total distance',
      '50% is the exact center, equidistant from both ends',
      '55 is considered an angel number, a signal of transition',
    ],
    source: 'Percentage',
  },
  {
    questionId: 'love-sound',
    values: [88, 10, 55, 25],
    meanings: [
      'A standard piano has 88 keys, spanning over seven octaves',
      '10 decibels is the threshold of human hearing, near silence',
      '55 decibels is the typical volume of laughter',
      'A whisper measures about 25 decibels',
    ],
    source: 'Decibels',
  },
  {
    questionId: 'love-weather',
    values: [58, 98, 96, 86],
    meanings: [
      '58% humidity is the comfort zone for most people',
      '98% humidity saturates the air, just short of rain',
      '96% humidity carries heavy pressure, oppressive and close',
      '86% humidity is the density that produces fog',
    ],
    source: 'Humidity',
  },
  {
    questionId: 'love-moon',
    values: [10, 14, 15, 22],
    meanings: [
      'Lunar day 1 begins the new moon, the start of the cycle',
      'Days 7 to 14 mark the waxing phase, building toward fullness',
      'Lunar day 15 is the full moon at peak illumination',
      'Lunar day 22 is the waning phase, light gradually receding',
    ],
    source: 'Lunar Age',
  },
  {
    questionId: 'love-fear',
    values: [13, 44, 78, 55],
    meanings: [
      'Tarot card 13 is Death, the fear of permanent ending',
      'The Five of Pentacles is card 44, isolation and rejection',
      'A full tarot deck has 78 cards, the whole spectrum of truth',
      'The Wheel of Fortune is card 55, unpredictable change',
    ],
    source: 'Tarot',
  },
  {
    questionId: 'love-gift',
    values: [22, 60, 33, 20],
    meanings: [
      '22 is the Master Builder in numerology, vision made real',
      'Temperance is tarot card 60, the gift of balance and patience',
      '33 is the Master Teacher in numerology, compassion in action',
      'Judgement is tarot card 20, awakening to a new chapter',
    ],
    source: 'Master/Tarot',
  },
  {
    questionId: 'love-texture',
    values: [12, 95, 18, 93],
    meanings: [
      '12-momme silk is the standard weight for fine fabric',
      '9.5 on the Mohs scale is nearly diamond hardness',
      'Water has a molecular mass of 18, the basis of all fluidity',
      '93 is the number of Thelema, representing pure will',
    ],
    source: 'Mohs/Chem',
  },
  {
    questionId: 'love-direction',
    values: [1, 7, 9, 10],
    meanings: [
      'In Dante, 1 represents Earth, the starting point',
      "Dante's Purgatory has 7 terraces, each a stage of refinement",
      "Dante's Inferno descends through 9 circles",
      "Dante's Paradise ascends through 10 celestial spheres",
    ],
    source: 'Dante',
  },
  {
    questionId: 'love-animal',
    values: [55, 57, 8, 59],
    meanings: [
      'I Ching hexagram 55 is Abundance, the fullness of power',
      'Hexagram 57 is The Gentle, the quiet strength of wind',
      'Hexagram 8 is Holding Together, the loyalty of a pack',
      'Hexagram 59 is Dispersion, the freedom of release',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'deceased-presence',
    values: [25, 49, 68, 35],
    meanings: [
      'Humans spend about 25% of sleep in the dreaming REM stage',
      '49 is 7 times 7, a number tied to heightened perception',
      "68 is linked to somatic processing, the body's felt sense",
      '35mm is the classic film format for capturing moments',
    ],
    source: 'Physiology',
  },
  {
    questionId: 'deceased-teaching',
    values: [80, 83, 69, 67],
    meanings: [
      'In ASCII, 80 is the code for the letter P, for Patience',
      'ASCII code 83 represents S, for Strength',
      'ASCII code 69 represents E, standing here for Endurance',
      'ASCII code 67 represents C, for Courage',
    ],
    source: 'ASCII',
  },
  {
    questionId: 'deceased-season',
    values: [16, 28, 39, 51],
    meanings: [
      'ISO week 16 falls in mid-April, when spring settles in',
      'Week 28 is mid-July, the height of summer',
      'Week 39 is late September, the turn into autumn',
      'Week 51 is mid-December, deep in winter',
    ],
    source: 'ISO Weeks',
  },
  {
    questionId: 'deceased-time',
    values: [38, 62, 82, 99],
    meanings: [
      'A solar elevation of 38 degrees marks mid-morning light',
      '62 degrees of solar elevation is the strong light of afternoon',
      'Lead is element 82, heavy and settled like evening',
      '99% lunar illumination lights the darkest hours of night',
    ],
    source: 'Solar/Astro',
  },
  {
    questionId: 'deceased-object',
    values: [56, 37, 48, 43],
    meanings: [
      'I Ching hexagram 56 is The Wanderer, carrying stories abroad',
      'Hexagram 37 is The Family, bonds that hold across distance',
      'Hexagram 48 is The Well, a source that never runs dry',
      'Hexagram 43 is Breakthrough, a decisive opening',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'deceased-place',
    values: [41, 57, 73, 97],
    meanings: [
      '41 is an irregular prime, a number with hidden structure',
      "57 is Grothendieck's prime, famously mistaken for ordinary",
      '73 is a star prime, a number radiating outward',
      '97 is the largest two-digit prime, the edge of a new order',
    ],
    source: 'Prime',
  },
  {
    questionId: 'deceased-element',
    values: [91, 87, 92, 81],
    meanings: [
      'Protactinium is element 91, rare and enduring',
      'Francium is element 87, the most unstable natural element',
      'Uranium is element 92, dense with stored energy',
      'Thallium is element 81, heavy and persistent',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'deceased-sound',
    values: [22, 55, 12, 57],
    meanings: [
      'In Human Design, Gate 22 is Grace, the gate of openness to music',
      'Gate 55 is Spirit, carrying an innate capacity for joy',
      'Gate 12 is Standstill, the eloquence found in silence',
      'Gate 57 is The Gentle Wind, the intuition of natural sounds',
    ],
    source: 'Human Design',
  },
  {
    questionId: 'deceased-scent',
    values: [2, 4, 7, 12],
    meanings: [
      'Ethyl acetate has a 2-carbon chain and smells of fruit and flowers',
      'Butyric acid has 4 carbons and carries the scent of aged food',
      'Benzoates have 7 carbons and produce warm, resinous fragrance',
      'Geosmin has 12 carbons, the compound that creates petrichor',
    ],
    source: 'Carbon Chain',
  },
  {
    questionId: 'deceased-message',
    values: [86, 36, 55, 53],
    meanings: [
      'Radon is element 86, an invisible gas that passes through walls',
      'Krypton is element 36, named for the Greek word for hidden',
      'Cesium is element 55, used in atomic clocks for precise timing',
      'Iodine is element 53, known for its strong resonant violet color',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'deceased-emotion',
    values: [44, 30, 58, 33],
    meanings: [
      'In Human Design, Gate 44 is Meeting, the recognition of patterns',
      'Gate 30 is Clinging Fire, intensity of feeling that sustains',
      'Gate 58 is Vitality, the drive toward joyful aliveness',
      'Gate 33 is Retreat, finding peace through reflection',
    ],
    source: 'Human Design',
  },
  {
    questionId: 'deceased-gift',
    values: [52, 17, 47, 45],
    meanings: [
      'Messier 52 is a star cluster in Cassiopeia, visible in winter',
      'Messier 17 is the Omega Nebula, a birthplace of new stars',
      'Messier 47 is an open cluster, stars loosely gathered together',
      'Messier 45 is the Pleiades, the Seven Sisters of the night sky',
    ],
    source: 'Messier',
  },
  {
    questionId: 'deceased-color',
    values: [98, 42, 79, 56],
    meanings: [
      'Chalk reflects 98% of light, the brightest natural white',
      'The number 42 is linked to deep sky blue in color indexing',
      'Gold is element 79, the only naturally yellow metal',
      '560 nanometers is the wavelength of green light',
    ],
    source: 'Symbolic',
  },
  {
    questionId: 'deceased-distance',
    values: [19, 97, 13, 44],
    meanings: [
      'A 19mm macro lens captures subjects at intimate range',
      '97 represents the far horizon, the limit of sight',
      '13 is a compact focal point, close to the center',
      '44 provides coverage in every direction, omnidirectional',
    ],
    source: 'Spatial',
  },
  {
    questionId: 'deceased-word',
    values: [12, 31, 64, 85],
    meanings: [
      '12 is the midnight hour, the threshold between days',
      '31 is a prime number, indivisible by anything but itself',
      '64 is the number of hexagrams in the I Ching, a complete system',
      '85 evokes a matrix, the interconnection of all things',
    ],
    source: 'Abstract',
  },
  {
    questionId: 'future-timeline',
    values: [11, 32, 50, 83],
    meanings: [
      'Sodium is element 11, highly reactive and immediate',
      'Germanium is element 32, a semiconductor that grows steadily',
      'Tin is element 50, traditionally the jubilee milestone',
      'Bismuth is element 83, the last stable element on the table',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'future-quality',
    values: [26, 51, 64, 15],
    meanings: [
      'I Ching hexagram 26 is Great Taming, disciplined accumulation',
      'Hexagram 51 is Shock, the courage born of sudden awakening',
      'Hexagram 64 is Before Completion, wisdom in the final approach',
      'Hexagram 15 is Modesty, quiet power that endures',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'future-dwelling',
    values: [13, 17, 12, 10],
    meanings: [
      "Aluminum is element 13, the most abundant metal in Earth's crust",
      'Chlorine is element 17, essential to salt and the sea',
      'Magnesium is element 12, at the center of every chlorophyll molecule',
      'Neon is element 10, the gas that lights up city signs',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'future-released',
    values: [20, 19, 15, 29],
    meanings: [
      'Bach flower 20 is Mimulus, the remedy for known fears',
      'Bach flower 19 is Larch, the remedy for self-doubt',
      'Bach flower 15 is Holly, the remedy for anger and resentment',
      'Bach flower 29 is Star of Bethlehem, the remedy for grief and shock',
    ],
    source: 'Bach Flower',
  },
  {
    questionId: 'future-morning',
    values: [14, 34, 52, 59],
    meanings: [
      'In Human Design, Gate 14 is Power Skills, the capacity to create',
      'Gate 34 is Power and Activity, pure productive energy',
      'Gate 52 is The Mountain, the ability to be completely still',
      'Gate 59 is Intimacy, the drive to dissolve barriers',
    ],
    source: 'Human Design',
  },
  {
    questionId: 'future-surprise',
    values: [63, 28, 39, 41],
    meanings: [
      '639 Hz is the Solfeggio frequency of connection, reduced to 63',
      '285 Hz is the Solfeggio frequency of renewal, reduced to 28',
      '396 Hz is the Solfeggio frequency of liberation, reduced to 39',
      '417 Hz is the Solfeggio frequency of change, reduced to 41',
    ],
    source: 'Solfeggio (reduced)',
  },
  {
    questionId: 'future-element',
    values: [16, 80, 22, 54],
    meanings: [
      'Sulfur is element 16, the ancient brimstone of transformation',
      'Mercury is element 80, the only metal that flows as liquid',
      'Titanium is element 22, strong as steel at half the weight',
      'Xenon is element 54, a noble gas that glows bright blue',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'future-color',
    values: [99, 11, 55, 46],
    meanings: [
      '99 represents maximum brightness, as close to pure light as possible',
      '11 in hexadecimal is deep dark, the near-absence of light',
      '550 nanometers is the wavelength of golden-yellow light',
      '460 nanometers is the wavelength of deep blue light',
    ],
    source: 'Color/Light',
  },
  {
    questionId: 'future-work',
    values: [55, 60, 90, 88],
    meanings: [
      'The 5th astrological house governs creativity and self-expression',
      'The 6th house governs health, service, and daily practice',
      'The 9th house governs philosophy, teaching, and higher learning',
      'The Midheaven is the highest point in a chart, governing public role',
    ],
    source: 'Astrology',
  },
  {
    questionId: 'future-company',
    values: [95, 30, 91, 40],
    meanings: [
      '95% is the standard confidence interval in statistics, near certainty',
      '30 is the minimum sample size for meaningful analysis',
      '91 is a prime number, singular and indivisible',
      '40 is the origin of the word quarantine, days of isolation',
    ],
    source: 'Math/Stats',
  },
  {
    questionId: 'future-pace',
    values: [45, 76, 24, 88],
    meanings: [
      '45 beats per minute is Largo, the slowest common tempo',
      '76 beats per minute is Andante, a walking pace',
      '24 frames per second is the speed of cinematic motion',
      '88 piano keys define the fixed range of the instrument',
    ],
    source: 'BPM',
  },
  {
    questionId: 'future-advice',
    values: [77, 44, 38, 66],
    meanings: [
      '77 is traditionally a number of protection and reassurance',
      '44 represents structural stability, a solid foundation',
      '38 carries the energy of risk and willingness to dare',
      '66 is associated with home, comfort, and restoration',
    ],
    source: 'Symbology',
  },
  {
    questionId: 'future-sacrifice',
    values: [21, 47, 72, 18],
    meanings: [
      'I Ching hexagram 21 is Biting Through, cutting away what resists',
      'Hexagram 47 is Oppression, enduring what weighs you down',
      'Hexagram 72 represents the collective, the opinion of the group',
      'Hexagram 18 is Work on What Has Been Spoiled, repairing the past',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'future-gain',
    values: [68, 33, 42, 69],
    meanings: [
      '68 represents expression and flow, unobstructed movement',
      '33 is the master number of compassion in numerology',
      '42 is the answer to life, the universe, and everything',
      '69 evokes the yin-yang symbol, opposing forces in balance',
    ],
    source: 'Symbology',
  },
  {
    questionId: 'future-animal',
    values: [53, 25, 67, 75],
    meanings: [
      'Iodine is element 53, a violet vapor associated with vision',
      'Manganese is element 25, found deep in the earth and caves',
      'Holmium is element 67, the most magnetic natural element',
      'Rhenium is element 75, one of the densest metals on earth',
    ],
    source: 'Periodic',
  },
  {
    questionId: 'universe-pattern',
    values: [21, 2, 5, 3],
    meanings: [
      'The World is tarot card XXI, the completion of a full cycle',
      'The High Priestess is card II, the keeper of hidden knowledge',
      'The Hierophant is card V, the bridge between seen and unseen',
      'The Empress is card III, the creative force of nature',
    ],
    source: 'Tarot Major Arcana',
  },
  {
    questionId: 'universe-celestial',
    values: [93, 38, 43, 27],
    meanings: [
      'Earth orbits the Sun at 93 million miles, exactly one AU',
      'The Moon is roughly 384,000 km from Earth',
      'Alpha Centauri is 4.3 light-years away, the nearest star system',
      'The cosmic background radiation has a temperature of 2.725 Kelvin',
    ],
    source: 'Astronomy',
  },
  {
    questionId: 'universe-symbol',
    values: [62, 16, 60, 27],
    meanings: [
      'Tau is 6.283, the full-circle constant equal to two pi',
      'The golden ratio is 1.618, the spiral constant found in nature',
      '60 degrees is the interior angle of every equilateral triangle',
      "Euler's number is 2.718, the base of natural growth and decay",
    ],
    source: 'Math Constants',
  },
  {
    questionId: 'universe-element',
    values: [4, 9, 3, 7],
    meanings: [
      'In Hebrew gematria, Esh (fire) reduces to 4',
      'Mayim (water) reduces to 9 in Hebrew gematria',
      'Aretz (earth) reduces to 3 in Hebrew gematria',
      'Ruach (air, or spirit) reduces to 7 in Hebrew gematria',
    ],
    source: 'Hebrew Gematria',
  },
  {
    questionId: 'universe-time',
    values: [1, 10, 7, 4],
    meanings: [
      'The Ascendant is the 1st house, where the sun rises in a chart',
      "The Midheaven is the 10th house, the sun's highest point at noon",
      'The Descendant is the 7th house, where the sun sets',
      "The Imum Coeli is the 4th house, the sun's lowest point at midnight",
    ],
    source: 'Astrology Houses',
  },
  {
    questionId: 'universe-trust',
    values: [5, 53, 25, 4],
    meanings: [
      'I Ching hexagram 5 is Waiting, trusting the right moment will come',
      'Hexagram 53 is Gradual Development, trust in steady progress',
      'Hexagram 25 is Innocence, trusting your own true nature',
      'Hexagram 4 is Youthful Folly, the willingness to embrace not knowing',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'universe-season',
    values: [79, 17, 26, 35],
    meanings: [
      'Day 79 of the year falls around March 20, the spring equinox',
      'Day 172 falls around the summer solstice in late June',
      'Day 265 falls around late September, the autumn equinox',
      'Day 355 falls in late December, near the winter solstice',
    ],
    source: 'Day Number',
  },
  {
    questionId: 'universe-lesson',
    values: [3, 17, 60, 42],
    meanings: [
      'I Ching hexagram 3 is Difficulty, persevering through early struggle',
      'Hexagram 17 is Following, the strength in yielding to what is',
      'Hexagram 60 is Limitation, knowing where to draw the line',
      'Hexagram 42 is Increase, trusting that more is coming',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'universe-gift',
    values: [6, 79, 30, 82],
    meanings: [
      'Carbon is element 6, the basis of diamonds and all organic life',
      'Gold is element 79, treasured across every civilization',
      'Zinc is element 30, essential to immune function and healing',
      'Lead is element 82, the alchemical starting point for turning base into gold',
    ],
    source: 'Periodic Table',
  },
  {
    questionId: 'universe-direction',
    values: [47, 11, 30, 3],
    meanings: [
      'Mercury orbits at 47 km/s, the fastest planet, pulled sunward',
      'Escape velocity from Earth is 11 km/s, the speed to break free',
      'Earth orbits at 30 km/s, a steady pace around the sun',
      'Geostationary orbit requires just 3 km/s, perfectly balanced and still',
    ],
    source: 'Orbital Velocity',
  },
  {
    questionId: 'universe-portal',
    values: [11, 22, 44, 88],
    meanings: [
      '11 is a master number, called the gateway of illumination',
      '22 is a master number, called the number of the visionary',
      '44 is a master number, representing a doubled foundation',
      '88 is a master number, evoking infinite potential',
    ],
    source: 'Numerology',
  },
  {
    questionId: 'universe-number',
    values: [1, 6, 28, 66],
    meanings: [
      'The 1st triangular number is simply 1',
      'The 3rd triangular number is 6, the sum of 1 plus 2 plus 3',
      'The 7th triangular number is 28, which is also a perfect number',
      'The 11th triangular number is 66, the sum of 1 through 11',
    ],
    source: 'Triangular Numbers',
  },
  {
    questionId: 'universe-animal',
    values: [36, 50, 39, 20],
    meanings: [
      'I Ching hexagram 36 is Darkening of the Light, intelligence in shadow',
      'Hexagram 50 is The Cauldron, transformation through sustained heat',
      'Hexagram 39 is Obstruction, finding a way through difficulty',
      'Hexagram 20 is Contemplation, insight gained through observation',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'universe-moon',
    values: [30, 8, 15, 23],
    meanings: [
      'In Vedic time, Amavasya is the 30th lunar day, the new moon',
      'Ashtami is the 8th lunar day, the first quarter moon',
      'Purnima is the 15th lunar day, the full moon',
      'Krishna Ashtami is the 23rd lunar day, the last quarter moon',
    ],
    source: 'Vedic Time',
  },
  {
    questionId: 'universe-sound',
    values: [40, 5, 80, 20],
    meanings: [
      '40 decibels is the level of a low, steady hum',
      '5 decibels is near-total silence, like an empty recording studio',
      '80 decibels is the volume of loud music in a busy room',
      '20 decibels is the volume of a quiet whisper',
    ],
    source: 'Decibels',
  },
  {
    questionId: 'decision-paths',
    values: [12, 13, 60, 10],
    meanings: [
      '12 is the number of the zodiac, built on duality and polarity',
      '13 encodes the triad and cycles, one beyond the complete 12',
      '60 is the base of Babylonian counting, suited to many divisions',
      '10 is the return to unity, the monad at its resting point',
    ],
    source: 'Number Theory',
  },
  {
    questionId: 'decision-fear',
    values: [7, 32, 2, 1],
    meanings: [
      'I Ching hexagram 7 is The Army, fear channeled into discipline',
      'Hexagram 32 is Duration, the fear of change met with constancy',
      'Hexagram 2 is The Receptive, the vast emptiness of the void',
      'Hexagram 1 is The Creative, the raw force of heaven itself',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'decision-stakes',
    values: [96, 10, 12, 14],
    meanings: [
      'The brow chakra has 96 petals, governing perception and clarity',
      'The solar plexus has 10 petals, governing the sense of self',
      'The heart chakra has 12 petals, governing connection',
      'The root chakra has 14 petals, governing survival and security',
    ],
    source: 'Chakra Petals',
  },
  {
    questionId: 'decision-younger',
    values: [6, 23, 28, 60],
    meanings: [
      'Aquila is IAU constellation 6, the eagle in flight',
      'Cancer is IAU constellation 23, the crab with its protective shell',
      'Columba is IAU constellation 28, the dove of peace',
      'Pegasus is IAU constellation 60, the winged horse of freedom',
    ],
    source: 'Constellations',
  },
  {
    questionId: 'decision-regret',
    values: [46, 52, 61, 40],
    meanings: [
      'I Ching hexagram 46 is Pushing Upward, rising by persistent effort',
      'Hexagram 52 is Keeping Still, the discipline of staying put',
      'Hexagram 61 is Inner Truth, the honesty of speaking from the center',
      'Hexagram 40 is Deliverance, the relief of finally letting go',
    ],
    source: 'I Ching',
  },
  {
    questionId: 'decision-body',
    values: [7, 12, 20, 16],
    meanings: [
      'The Chariot is tarot card 7, forward momentum through willpower',
      'The Hanged Man is card 12, surrender and seeing things differently',
      'Judgement is card 20, rising to answer a call',
      'The Tower is card 16, sudden collapse that clears the way',
    ],
    source: 'Tarot',
  },
  {
    questionId: 'decision-weather',
    values: [12, 10, 50, 85],
    meanings: [
      'The troposphere extends to 12 km, where all weather occurs',
      'Surface haze forms at 10 km or below, limiting visibility',
      'The stratosphere reaches 50 km, calm and clear above the storms',
      'The mesopause sits at 85 km, the coldest layer of the atmosphere',
    ],
    source: 'Atmosphere (km)',
  },
  {
    questionId: 'decision-color',
    values: [95, 40, 16, 19],
    meanings: [
      'In alchemy, 95 corresponds to Rubedo, the reddening of completion',
      '40 is Mem in alchemical tradition, the letter of water and blue',
      '16 is Cinereus, the gray of ash left after the fire',
      '19 is solar perfection in alchemy, the gold of the final stage',
    ],
    source: 'Alchemy',
  },
  {
    questionId: 'decision-element',
    values: [15, 24, 18, 21],
    meanings: [
      'Fire signs (Aries, Leo, Sagittarius) sum to 15 in the zodiac',
      'Water signs (Cancer, Scorpio, Pisces) sum to 24',
      'Earth signs (Taurus, Virgo, Capricorn) sum to 18',
      'Air signs (Gemini, Libra, Aquarius) sum to 21',
    ],
    source: 'Astrology',
  },
  {
    questionId: 'decision-time',
    values: [5, 6, 7, 9],
    meanings: [
      '10 to the 5th seconds is roughly one day',
      '10 to the 6th seconds is roughly one month',
      '10 to the 7th seconds is roughly one year',
      '10 to the 9th seconds spans a human lifetime',
    ],
    source: 'Physics',
  },
  {
    questionId: 'decision-advisor',
    values: [5, 6, 7, 1],
    meanings: [
      'In biological taxonomy, rank 5 is Family, the closest group',
      'Rank 6 is Genus, the shared lineage of near relatives',
      'Rank 7 is Species, the individual self',
      'Rank 1 is Domain, the broadest and most distant classification',
    ],
    source: 'Taxonomy',
  },
  {
    questionId: 'decision-lose',
    values: [18, 8, 6, 1],
    meanings: [
      'Argon is element 18, a stable noble gas that rarely reacts',
      'Oxygen is element 8, the element of bonding and connection',
      'Carbon is element 6, the foundation of all living things',
      'Hydrogen is element 1, the simplest and most fundamental atom',
    ],
    source: 'Chemistry',
  },
  {
    questionId: 'decision-gain',
    values: [3, 4, 5, 6],
    meanings: [
      'Lithium is element 3, the lightest metal, simple and reactive',
      'Beryllium is element 4, harder and more structured',
      'Boron is element 5, bridging metals and nonmetals',
      'Carbon is element 6, the most complex builder of life',
    ],
    source: 'Atomic Period 2',
  },
  {
    questionId: 'decision-moon',
    values: [2, 3, 5, 7],
    meanings: [
      '2 is the first prime, the only even one, a symbol of duality',
      '3 is the prime of synthesis, the first odd prime',
      '5 is the prime of change, the number of the senses',
      '7 is the prime of completion, indivisible and whole',
    ],
    source: 'Prime',
  },
  {
    questionId: 'decision-animal',
    values: [4, 1, 2, 3],
    meanings: [
      'Ansuz is rune 4, the rune of the raven and divine messages',
      'Fehu is rune 1, the rune of the fox and resourcefulness',
      'Uruz is rune 2, the rune of the bear and primal strength',
      'Thurisaz is rune 3, the rune of the thorn and fierce defense',
    ],
    source: 'Runes',
  },
  {
    questionId: 'purpose-gift',
    values: [6, 22, 8, 16],
    meanings: [
      'Kenaz is rune 6, the torch that illuminates what was hidden',
      'Inguz is rune 22, the seed carrying all potential within',
      'Wunjo is rune 8, the rune of joy and deep fulfillment',
      'Sowilo is rune 16, the sun rune of vitality and healing',
    ],
    source: 'Runes',
  },
  {
    questionId: 'purpose-alive',
    values: [5, 7, 9, 6],
    meanings: [
      'The 5th astrological house governs creativity and play',
      'The 7th house governs partnerships and one-to-one connection',
      'The 9th house governs philosophy and the search for meaning',
      'The 6th house governs service and devotion to craft',
    ],
    source: 'Astrology',
  },
  {
    questionId: 'purpose-impact',
    values: [3, 4, 6, 9],
    meanings: [
      'Binah is the 3rd sephirah in Kabbalah, the seat of understanding',
      'Chesed is the 4th sephirah, the sphere of loving-kindness',
      'Tiphereth is the 6th sephirah, the center of beauty and harmony',
      'Yesod is the 9th sephirah, the foundation that connects all above to below',
    ],
    source: 'Kabbalah',
  },
  {
    questionId: 'purpose-thanks',
    values: [9, 5, 4, 6],
    meanings: [
      'Enneagram type 9 is the Peacemaker, creating calm for others',
      'Type 5 is the Observer, offering depth of perception',
      'Type 4 is the Individualist, bringing authenticity and feeling',
      'Type 6 is the Loyalist, providing steadfast support',
    ],
    source: 'Enneagram',
  },
  {
    questionId: 'purpose-free',
    values: [16, 18, 14, 20],
    meanings: [
      'BUILD sums to 16 in Chaldean numerology',
      'TEACH sums to 18 in Chaldean numerology',
      'HEAL sums to 14 in Chaldean numerology',
      'CREATE sums to 20 in Chaldean numerology',
    ],
    source: 'Numerology',
  },
  {
    questionId: 'purpose-child',
    values: [9, 7, 6, 1],
    meanings: [
      'Sagittarius is the 9th sign, the explorer of the zodiac',
      'Libra is the 7th sign, the artist seeking balance and beauty',
      'Virgo is the 6th sign, the helper devoted to improvement',
      'Aries is the 1st sign, the leader who charges ahead',
    ],
    source: 'Zodiac',
  },
  {
    questionId: 'purpose-element',
    values: [4, 20, 6, 8],
    meanings: [
      'A tetrahedron has 4 faces, the simplest Platonic solid, linked to fire',
      'An icosahedron has 20 faces, the most complex Platonic solid, linked to water',
      'A cube has 6 faces, the most stable Platonic solid, linked to earth',
      'An octahedron has 8 faces, balanced and symmetrical, linked to air',
    ],
    source: 'Sacred Geometry',
  },
  {
    questionId: 'purpose-color',
    values: [79, 27, 29, 22],
    meanings: [
      'Gold is element 79, the alchemical metal of the sun',
      'Cobalt is element 27, the source of deep blue pigment',
      'Copper is element 29, which oxidizes into green malachite',
      'Titanium is element 22, the source of brilliant white pigment',
    ],
    source: 'Alchemy',
  },
  {
    questionId: 'purpose-scale',
    values: [1, 27, 50, 98],
    meanings: [
      '1 Hz is an extremely low frequency, resonating with the Earth itself',
      '27 MHz is the citizens band radio range, for local community',
      '50 MHz is the amateur radio band, reaching across continents',
      '98 MHz is the FM broadcast range, transmitting to millions',
    ],
    source: 'Radio',
  },
  {
    questionId: 'purpose-tool',
    values: [12, 8, 10, 20],
    meanings: [
      'Cranial nerve XII is the hypoglossal, controlling the tongue and speech',
      'The C8 nerve controls fine hand movement and dexterity',
      'Cranial nerve X is the vagus, connecting brain to heart and gut',
      '20 Hz beta waves correspond to focused, active thinking',
    ],
    source: 'Physiology',
  },
  {
    questionId: 'purpose-block',
    values: [2, 12, 18, 4],
    meanings: [
      'Bach flower 2 is Aspen, the remedy for unnamed, creeping fear',
      'Bach flower 12 is Gentian, the remedy for doubt after setback',
      'Bach flower 18 is Impatiens, the remedy for frustration with time',
      'Bach flower 4 is Centaury, the remedy for losing yourself to others',
    ],
    source: 'Bach Flower',
  },
  {
    questionId: 'purpose-space',
    values: [5, 2, 4, 6],
    meanings: [
      'In feng shui, the center (5) governs health and balance',
      'Kun (2) is the southwest sector, governing relationships',
      'Xun (4) is the southeast sector, the area of wood and nature',
      'Qian (6) is the northwest sector, linked to heaven and leadership',
    ],
    source: 'Feng Shui',
  },
  {
    questionId: 'purpose-time',
    values: [40, 10, 6, 2],
    meanings: [
      'Gamma waves at 40 Hz are the brainwaves of peak focus and insight',
      'Alpha waves at 10 Hz are the brainwaves of relaxed alertness',
      'Theta waves at 6 Hz are the brainwaves of deep creativity and dreams',
      'Delta waves at 2 Hz are the brainwaves of dreamless, restorative sleep',
    ],
    source: 'Brain Waves',
  },
  {
    questionId: 'purpose-ancestor',
    values: [1, 4, 2, 5],
    meanings: [
      'The root chakra (1) governs survival and physical grounding',
      'The heart chakra (4) governs love, compassion, and service',
      'The sacral chakra (2) governs creativity and emotional flow',
      'The throat chakra (5) governs expression and speaking truth',
    ],
    source: 'Chakras',
  },
  {
    questionId: 'purpose-animal',
    values: [1, 15, 70, 90],
    meanings: [
      'A honeybee lives about 1 year, brief and intensely productive',
      'A lion lives about 15 years in the wild',
      'An elephant lives about 70 years, with deep social memory',
      'A bowhead whale can live over 90 years, the longest of any mammal',
    ],
    source: 'Zoology',
  },
  {
    questionId: 'ground-light',
    values: [15, 80, 35, 4],
    meanings: [
      'A forest canopy reflects about 15% of incoming light',
      'Fresh snow reflects about 80% of light, almost blinding',
      'Sand reflects about 35% of light, a soft diffuse glow',
      'Charcoal absorbs nearly everything, reflecting only 4%',
    ],
    source: 'Albedo (%)',
  },
  {
    questionId: 'ground-breath',
    values: [14, 32, 28, 6],
    meanings: [
      '14 breaths per minute is a normal, relaxed respiratory rate',
      '32 breaths per minute indicates physiological stress',
      '28 breaths per minute is tachypnea, rapid and shallow',
      '6 breaths per minute is deep meditative breathing',
    ],
    source: 'Respiratory (BPM)',
  },
  {
    questionId: 'ground-moment-color',
    values: [6, 43, 20, 9],
    meanings: [
      'Pigment White 6 is titanium white, the clearest white in painting',
      'Pigment Yellow 43 is yellow ochre, an ancient earth tone',
      'Pigment Orange 20 is cadmium orange, vivid and saturated',
      'Pigment Black 9 is ivory black, the deepest warm dark',
    ],
    source: 'Pigment Codes',
  },
  {
    questionId: 'ground-body',
    values: [3, 47, 69, 32],
    meanings: [
      "GABA has a molecular weight of 103, the body's main calming signal",
      'Glutamate has a molecular weight of 147, the main excitatory signal',
      'Norepinephrine has a molecular weight of 169, the alertness chemical',
      'Melatonin has a molecular weight of 232, the signal for sleep',
    ],
    source: 'Biochemistry',
  },
  {
    questionId: 'ground-spaciousness',
    values: [60, 30, 96, 24],
    meanings: [
      'A French door is 60 inches wide, generous and welcoming',
      'A standard interior door is 30 inches wide',
      'A grand entrance door is 96 inches wide, ceremonially open',
      'A closet door is 24 inches wide, compact and enclosed',
    ],
    source: 'Door Widths (in)',
  },
  {
    questionId: 'ground-time-feel',
    values: [60, 24, 30, 1],
    meanings: [
      '60 fps is high-motion video, smooth and fast-moving',
      '24 fps is the classic cinematic frame rate, slightly dreamlike',
      '30 fps is the standard broadcast rate, steady and familiar',
      '1 fps is timelapse speed, time compressed to near-stillness',
    ],
    source: 'Frame Rates (FPS)',
  },
  {
    questionId: 'ground-hands',
    values: [76, 65, 98, 70],
    meanings: [
      '76 degrees Fahrenheit is a comfortable indoor warmth',
      '65 degrees is a cool, air-conditioned chill',
      '98 degrees is near body temperature, the edge of a heat wave',
      '70 degrees is ambient room temperature, neither warm nor cool',
    ],
    source: 'Thermostat (°F)',
  },
  {
    questionId: 'ground-feeling',
    values: [9, 63, 35, 10],
    meanings: [
      'In Human Design, Gate 9 is the gate of focus and concentration',
      'Gate 63 is the gate of inquiry, the drive to question',
      'Gate 35 is the gate of progress, seeking new experience',
      'Gate 10 is the gate of self-love, authenticity in behavior',
    ],
    source: 'Human Design',
  },
  {
    questionId: 'ground-texture',
    values: [10, 90, 20, 70],
    meanings: [
      'Talc is 1 on the Mohs scale, the softest mineral known',
      'Corundum is 9 on the Mohs scale, nearly as hard as diamond',
      'Gypsum is 2 on the Mohs scale, soft enough to scratch with a fingernail',
      'Quartz is 7 on the Mohs scale, hard enough to scratch glass',
    ],
    source: 'Mohs (×10)',
  },
  {
    questionId: 'ground-space-energy',
    values: [1, 7, 11, 12],
    meanings: [
      'Unison is interval 1, two notes sounding as one',
      'A perfect fifth is 7 semitones, the most resonant interval',
      'A major seventh is 11 semitones, bright and reaching upward',
      'An octave is 12 semitones, the same note doubled in frequency',
    ],
    source: 'Music Intervals',
  },
  {
    questionId: 'ground-surroundings',
    values: [50, 99, 14, 85],
    meanings: [
      "A 50mm lens matches the human eye's natural field of view",
      'A 99mm telephoto lens compresses distance, pulling the far close',
      'A 14mm ultra-wide lens captures nearly everything in sight',
      'An 85mm lens is the classic portrait focal length, intimate and clear',
    ],
    source: 'Camera Lenses (mm)',
  },
  {
    questionId: 'ground-eyes',
    values: [10, 64, 4, 16],
    meanings: [
      'ISO 100 is daylight film speed, crisp and fine-grained',
      'ISO 6400 is high-sensitivity film, designed for darkness',
      'ISO 400 is action film speed, fast enough to freeze motion',
      'ISO 1600 is grainy film, adding visible texture to the image',
    ],
    source: 'ISO Sensitivity',
  },
  {
    questionId: 'weird-number',
    values: [9, 21, 33, 66],
    meanings: [
      '3 times 3 equals 9, the sacred triple of a triple',
      '7 times 3 equals 21, traditionally the number of fortune',
      '11 times 3 equals 33, considered the master teacher number',
      '22 times 3 equals 66, associated with cosmic responsibility',
    ],
    source: 'Triplicities',
  },
  {
    questionId: 'weird-weather',
    values: [1, 61, 95, 45],
    meanings: [
      'WMO code 01 means clouds are dissolving, sky clearing',
      'WMO code 61 is a light, continuous rain',
      'WMO code 95 is a thunderstorm with moderate intensity',
      'WMO code 45 is fog, visibility below one kilometer',
    ],
    source: 'WMO/SYNOP Codes',
  },
  {
    questionId: 'weird-animal',
    values: [29, 30, 23, 25],
    meanings: [
      '2029 is the next Year of the Rooster in the Chinese zodiac',
      '2030 is the next Year of the Dog',
      '2023 was the most recent Year of the Rabbit',
      '2025 is the Year of the Snake',
    ],
    source: 'Chinese Zodiac Year',
  },
  {
    questionId: 'weird-direction',
    values: [4, 2, 1, 3],
    meanings: [
      'In Mahjong, East is wind 1, the starting position',
      'South is wind 2 in Mahjong',
      'West is wind 3 in Mahjong',
      'North is wind 4, the final position in the cycle',
    ],
    source: 'Mahjong',
  },
  {
    questionId: 'weird-door',
    values: [30, 50, 90, 10],
    meanings: [
      'RAL 3000-series colors are reds, bold and attention-grabbing',
      'RAL 5000-series colors are blues, cool and receding',
      'RAL 9000-series colors are blacks and whites, the extremes',
      'RAL 1000-series colors are yellows and golds, warm and bright',
    ],
    source: 'RAL Colors',
  },
  {
    questionId: 'weird-key',
    values: [5, 99, 3, 1],
    meanings: [
      'In chess, a rook is valued at 5 points, the strength of a castle',
      "The king's value is infinite, reduced here to 99",
      'A bishop is valued at 3 points, moving on diagonals of memory',
      'A pawn is valued at 1 point, the smallest piece on the board',
    ],
    source: 'Chess',
  },
]

/** Get all coordinate mappings as a Map keyed by question ID */
export function getStaticCoordinateMappings(): Map<string, CoordinateMapping> {
  const map = new Map<string, CoordinateMapping>()
  for (const m of STATIC_MAPPINGS) {
    map.set(m.questionId, m)
  }
  return map
}
