-- Coordinate Mappings
-- Thematic number mappings for coordinate questions.
-- Source: docs/COORDINATE-MAPPINGS.md
-- Generated by scripts/generate-mappings-sql.ts

-- Create table
CREATE TABLE IF NOT EXISTS coordinate_mappings (
  question_id TEXT PRIMARY KEY,
  option_values JSONB NOT NULL,
  option_meanings JSONB NOT NULL,
  source TEXT NOT NULL
);

-- Ensure values and meanings arrays have matching lengths
DO $$ BEGIN
  ALTER TABLE coordinate_mappings
  ADD CONSTRAINT values_meanings_length_match
  CHECK (jsonb_array_length(option_values) = jsonb_array_length(option_meanings));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- RLS: public read, service role write
ALTER TABLE coordinate_mappings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS select_coordinate_mappings ON coordinate_mappings;
CREATE POLICY select_coordinate_mappings ON coordinate_mappings FOR SELECT USING (true);

-- Clear and re-insert all mappings (idempotent)
TRUNCATE coordinate_mappings;

-- Insert all mappings
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('cosmic-moon', '[24,34,14,23]', '["Hexagram 24 (Return)","34 (Great Power)","14 (Great Possession)","23 (Stripping Away)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('cosmic-element', '[26,18,14,78]', '["Fe(26) Mars metal","H₂O mass(18)","Si(14) crust base","N₂(78% atmosphere)"]', 'Periodic Table');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('cosmic-celestial', '[19,18,17,99]', '["Sun(XIX)","Moon(XVIII)","Star(XVII)","99 Omega/final limit"]', 'Tarot Major Arcana');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('cosmic-season-inner', '[11,30,33,29]', '["Peace(11)","Clinging Fire(30)","Retreat(33)","The Abysmal(29)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('cosmic-time', '[90,18,27,36]', '["East 90°","South 180°","West 270°","North 360°"]', 'Astronomy');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('color-draw', '[65,47,59,53]', '["650nm","470nm","590nm","530nm"]', 'Optics');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('color-warmth', '[27,65,40,50]', '["2700K","6500K","4000K","5000K balance"]', 'Kelvin');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('color-light', '[90,30,10,55]', '["snow 90%","charcoal 30%","Vantablack 10%","grey card 55%"]', 'Albedo');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('color-mood', '[96,64,85,42]', '["Crown 963Hz","Heart 639Hz","Third Eye 852Hz","Sacral 417Hz"]', 'Solfeggio Hz');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('symbol-shape', '[31,18,61,30]', '["Pi 3.14","180° sum","Phi 1.618","Speed of light 3.0×10⁸"]', 'Math Constants');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('symbol-direction', '[36,18,90,27]', '["360°","180°","90°","270°"]', 'Compass Degrees');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('symbol-number', '[33,77,99,21]', '["33 master number (3×11)","77 master number (7×11)","99 master number (9×11)","21 The World / completion mirrored"]', 'Numerology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('symbol-animal', '[11,18,13,88]', '["Ace of Swords/Air(11)","Moon(18)","Death/Rebirth(13)","Strength doubled(88)"]', 'Tarot Archetype');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('symbol-object', '[29,47,19,14]', '["Cu(29)","Ag(47)","Sun association(19)","Si(14)"]', 'Material Science');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('emotional-weather', '[20,98,99,45]', '["1020hPa high","980hPa low","99% humidity","45mph wind"]', 'Meteorology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('emotional-energy', '[45,90,70,10]', '["45°","90°","270°→70","0°→10"]', 'Wave Physics');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('emotional-body', '[76,44,32,11]', '["7th+6th","4th doubled","3rd+2nd","1st+1st"]', 'Chakra System');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('emotional-need', '[21,32,54,89]', '["Octave 2:1","Perfect 5th 3:2","Major 3rd 5:4","Fibonacci 89"]', 'Music/Fibonacci');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-element', '[31,19,66,74]', '["Ga(31) low-melt","K(19) water-reactive","Dy(66) rare earth","W(74) dense/enduring"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-time', '[10,12,18,24]', '["10:00 morning","12:00 noon","18:00 evening","00:00 midnight"]', 'Clock (24h)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-word', '[52,85,63,46]', '["L+O+V+E = 12+15+22+5 = 54→52","T+R+U+T+H = 20+18+21+20+8 = 87→85","S+O+R+R+Y = 19+15+18+18+25 = 95→63","S+T+A+Y = 19+20+1+25 = 65→46"]', 'Gematria');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-color', '[65,47,79,49]', '["650nm red","Ag(47) reflection","Au(79) gold","In(49) lustrous"]', 'Periodic/Optics');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-body', '[72,40,27,20]', '["72bpm resting HR","40Hz gamma","27 hand bones","20/20 vision"]', 'Biology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-season', '[21,22,23,12]', '["Mar 21","Jun 22","Sep 23","December (12th month)"]', 'Solstice/Calendar');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-distance', '[10,99,50,55]', '["10% close","99% max","50% center","55 angel number"]', 'Percentage');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-sound', '[88,10,55,25]', '["88 piano keys","10dB silence","55dB laughter","25dB whisper"]', 'Decibels');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-weather', '[58,98,96,86]', '["58% comfort","98% saturation","96% heavy pressure","86% fog"]', 'Humidity');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-moon', '[10,14,15,22]', '["Day ~1","Day 7-14","Day 15","Day 22"]', 'Lunar Age');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-fear', '[13,44,78,55]', '["Death(13)","5 of Pentacles(44)","Full Deck(78)","Wheel of Fortune(55)"]', 'Tarot');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-gift', '[22,60,33,20]', '["Master Builder(22)","Temperance(60)","Master Teacher(33)","Judgement(20)"]', 'Master/Tarot');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-texture', '[12,95,18,93]', '["12 momme silk","9.5 hardness","H₂O mass 18","93 Thelema/Will"]', 'Mohs/Chem');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-direction', '[1,7,9,10]', '["Earth(1)","Terraces of Purgatory(7)","Circles of Hell(9)","Spheres of Heaven(10)"]', 'Dante');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('love-animal', '[55,57,8,59]', '["Feng(55) abundance/power","Sun(57) gentleness","Pi(8) holding together/pack loyalty","Huan(59) dispersion/flight"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-presence', '[25,49,68,35]', '["25% REM sleep","49=7×7 mystic perception","68 somatic processing","35mm film"]', 'Physiology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-teaching', '[80,83,69,67]', '["P(80)","S(83)","E(69)","C(67)"]', 'ASCII');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-season', '[16,28,39,51]', '["Week 16 (mid-April)","Week 28 (mid-July)","Week 39 (late September)","Week 51 (mid-December)"]', 'ISO Weeks');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-time', '[38,62,82,99]', '["38° solar elevation (morning)","62° solar elevation (afternoon)","Pb(82) settling/evening","99% lunar illumination (night)"]', 'Solar/Astro');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-object', '[56,37,48,43]', '["Wanderer(56)","Family(37)","The Well(48)","Breakthrough(43)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-place', '[41,57,73,97]', '["41 irregular prime","57 Grothendieck''s prime","73 star prime","97 largest two-digit prime"]', 'Prime');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-element', '[91,87,92,81]', '["Pa(91)","Fr(87)","U(92)","Tl(81) — heavy/enduring elements"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-sound', '[22,55,12,57]', '["Gate 22 (Grace/Music)","Gate 55 (Spirit/Joy)","Gate 12 (Standstill/Silence)","Gate 57 (Gentle Wind/Nature)"]', 'Human Design');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-scent', '[2,4,7,12]', '["ethyl acetate(2)","butyric acid(4)","benzoates(7)","geosmin(12)"]', 'Carbon Chain');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-message', '[86,36,55,53]', '["Rn(86) invisible","Kr(36) hidden","Cs(55) atomic clock","I(53) resonance"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-emotion', '[44,30,58,33]', '["Gate 44 (Meeting)","Gate 30 (Clinging Fire)","Gate 58 (Vitality)","Gate 33 (Retreat)"]', 'Human Design');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-gift', '[52,17,47,45]', '["M52 (Cassiopeia)","M17 (Omega)","M47 (Cluster)","M45 (Pleiades)"]', 'Messier');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-color', '[98,42,79,56]', '["98 albedo (chalk)","42 deep sky","Au(79)","560nm wavelength"]', 'Symbolic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-distance', '[19,97,13,44]', '["19mm macro lens","97 horizon","13 micro/core","44 omni-directional"]', 'Spatial');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('deceased-word', '[12,31,64,85]', '["12 midnight hour","31 prime/indivisible","64 completion","85 matrix/web"]', 'Abstract');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-timeline', '[11,32,50,83]', '["Na(11) reactive/now","Ge(32) solid growth","Sn(50) jubilee","Bi(83) last stable element"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-quality', '[26,51,64,15]', '["Great Taming(26)","Shock(51)","Before Completion(64)","Modesty(15)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-dwelling', '[13,17,12,10]', '["Al(13) crust","Cl(17) salt/sea","Mg(12) chlorophyll","Ne(10) lights"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-released', '[20,19,15,29]', '["Mimulus(20)","Larch(19)","Holly(15)","Star of Bethlehem(29)"]', 'Bach Flower');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-morning', '[14,34,52,59]', '["Gate 14 (Power Skills)","Gate 34 (Power/Activity)","Gate 52 (Mountain)","Gate 59 (Intimacy)"]', 'Human Design');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-surprise', '[63,28,39,41]', '["639Hz→63","285Hz→28","396Hz→39","417Hz→41"]', 'Solfeggio (reduced)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-element', '[16,80,22,54]', '["S(16) brimstone","Hg(80) liquid","Ti(22) strong earth","Xe(54) noble gas"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-color', '[99,11,55,46]', '["99 max brightness","11 hex dark","550nm gold range","460nm blue range"]', 'Color/Light');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-work', '[55,60,90,88]', '["5th House creativity","6th House health","9th House philosophy","Midheaven status"]', 'Astrology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-company', '[95,30,91,40]', '["95% confidence interval","30 sample threshold","91 prime/unitary","40 quarantine"]', 'Math/Stats');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-pace', '[45,76,24,88]', '["45 Largo","76 Andante","24 fps motion","88 piano keys/fixed"]', 'BPM');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-advice', '[77,44,38,66]', '["77 divine protection","44 structural stability","38 risk/daring","66 home/restoration"]', 'Symbology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-sacrifice', '[21,47,72,18]', '["Biting Through(21)","Oppression(47)","Collective(72)","Work on Spoiled(18)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-gain', '[68,33,42,69]', '["68 expression/flow","33 master compassion","42 answer to life","69 yin-yang balance"]', 'Symbology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('future-animal', '[53,25,67,75]', '["I(53) violet vapor/vision","Mn(25) earth/cave","Ho(67) magnetic/sonar","Re(75) dense/pack"]', 'Periodic');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-pattern', '[21,2,5,3]', '["The World(XXI) completion cycle","High Priestess(II) reflection/duality","Hierophant(V) gateway between worlds","Empress(III) creative weaving"]', 'Tarot Major Arcana');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-celestial', '[93,38,43,27]', '["Earth-Sun 93M miles (1 AU)","Earth-Moon 384k km","Alpha Centauri 4.3 light-years","CMB 2.725K (empty space)"]', 'Astronomy');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-symbol', '[62,16,60,27]', '["Tau (τ=6.283) circle constant","golden ratio (φ=1.618) spiral constant","60° equilateral triangle","Euler''s number (e=2.718) wave/exponential constant"]', 'Math Constants');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-element', '[4,9,3,7]', '["Esh(301→4)","Mayim(90→9)","Aretz(291→3)","Ruach(214→7)"]', 'Hebrew Gematria');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-time', '[1,10,7,4]', '["Ascendant(1)","Midheaven(10)","Descendant(7)","Imum Coeli(4)"]', 'Astrology Houses');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-trust', '[5,53,25,4]', '["Hsü(5) Waiting/trusting the right moment","Chien(53) gradual Development","Wu Wang(25) Innocence/trusting true nature","Meng(4) Youthful Folly/embracing unknowing"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-season', '[79,17,26,35]', '["Day 79 (Mar 20)","Day 172","Day 265","Day 355"]', 'Day Number');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-lesson', '[3,17,60,42]', '["Chun(3) persevering through difficulty","Sui(17) following/yielding","Chieh(60) proper limitation","I(42) trusting in increase"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-gift', '[6,79,30,82]', '["C(6) diamond/clarity","Au(79) gold of devotion","Zn(30) immune healing","Pb(82) alchemical lead-to-gold transformation"]', 'Periodic Table');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-direction', '[47,11,30,3]', '["Mercury/sunward(47)","escape velocity(11)","Earth orbital(30)","geostationary(3)"]', 'Orbital Velocity');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-portal', '[11,22,44,88]', '["11 gateway of illumination","22 visionary sight","44 foundation reflected","88 infinite potential"]', 'Numerology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-number', '[1,6,28,66]', '["T₁=1","T₃=6 (1+2+3)","T₇=28 (also a perfect number)","T₁₁=66 (1+2+...+11)"]', 'Triangular Numbers');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-animal', '[36,50,39,20]', '["Ming I(36) intelligence in darkness","Ting(50) transformation through fire","Chien(39) navigating obstruction","Kuan(20) contemplative observation"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-moon', '[30,8,15,23]', '["Amavasya(30)","Ashtami(8)","Purnima(15)","Krishna Ashtami(23)"]', 'Vedic Time');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('universe-sound', '[40,5,80,20]', '["40dB low hum","5dB studio silence","80dB loud music","20dB whisper"]', 'Decibels');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-paths', '[12,13,60,10]', '["12 duality/zodiac","13 triad/cycles","60 sexagesimal","10 monad/zero-point"]', 'Number Theory');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-fear', '[7,32,2,1]', '["Army(07) discipline","Duration(32) constancy","Receptive(02) void","Creative(01) heaven"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-stakes', '[96,10,12,14]', '["Brow 96 (perception)","Solar Plexus 10 (self)","Heart 12 (connection)","Root 14"]', 'Chakra Petals');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-younger', '[6,23,28,60]', '["Aquila(06) eagle","Cancer(23) shell","Columba(28) dove","Pegasus(60) wings"]', 'Constellations');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-regret', '[46,52,61,40]', '["Pushing Upward(46)","Keeping Still(52)","Inner Truth(61)","Deliverance(40)"]', 'I Ching');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-body', '[7,12,20,16]', '["Chariot(07)","Hanged Man(12)","Judgment(20)","Tower(16)"]', 'Tarot');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-weather', '[12,10,50,85]', '["Troposphere 12km","surface haze 10km","stratosphere 50km","mesopause 85km"]', 'Atmosphere (km)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-color', '[95,40,16,19]', '["95 Rubedo/completion","40 Mem/water","16 Cinereus/ash","19 solar perfection"]', 'Alchemy');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-element', '[15,24,18,21]', '["Fire(1+5+9=15)","Water(4+8+12=24)","Earth(2+6+10=18)","Air(3+7+11=21)"]', 'Astrology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-time', '[5,6,7,9]', '["10⁵ day","10⁶ month","10⁷ year","10⁹ lifetime"]', 'Physics');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-advisor', '[5,6,7,1]', '["05 Family","06 Genus","07 Species/Self","01 Domain"]', 'Taxonomy');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-lose', '[18,8,6,1]', '["Ar(18) stable/inert","O(08) bonding","C(06) life base","H(01) fundamental"]', 'Chemistry');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-gain', '[3,4,5,6]', '["Li(03)","Be(04)","B(05)","C(06) — increasing complexity"]', 'Atomic Period 2');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-moon', '[2,3,5,7]', '["2 first prime / duality","3 trinity / synthesis","5 quintessence / change","7 completion / mystery"]', 'Prime');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('decision-animal', '[4,1,2,3]', '["Ansuz(04) god/raven","Fehu(01) wealth/cunning","Uruz(02) strength/bear","Thurisaz(03) thorn/defense"]', 'Runes');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-gift', '[6,22,8,16]', '["Kenaz(06) torch","Inguz(22) seed","Wunjo(08) joy","Sowilo(16) sun/healing"]', 'Runes');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-alive', '[5,7,9,6]', '["5th creativity","7th partnerships","9th philosophy","6th service"]', 'Astrology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-impact', '[3,4,6,9]', '["Binah(03)","Chesed(04)","Tiphereth(06) harmony","Yesod(09) foundation"]', 'Kabbalah');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-thanks', '[9,5,4,6]', '["Peacemaker(09)","Observer(05)","Individualist(04)","Loyalist(06)"]', 'Enneagram');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-free', '[16,18,14,20]', '["BUILD(16)","TEACH(18)","HEAL(14)","CREATE(20)"]', 'Numerology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-child', '[9,7,6,1]', '["Sagittarius(09)","Libra(07)","Virgo(06)","Aries(01)"]', 'Zodiac');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-element', '[4,20,6,8]', '["Tetrahedron(04)","Icosahedron(20)","Cube(06)","Octahedron(08)"]', 'Sacred Geometry');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-color', '[79,27,29,22]', '["Au(79)","Co(27) blue","Cu(29) malachite","Ti(22) white"]', 'Alchemy');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-scale', '[1,27,50,98]', '["01Hz ELF/Earth","27MHz CB","50MHz Ham/DX","98MHz FM broadcast"]', 'Radio');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-tool', '[12,8,10,20]', '["CN XII hypoglossal/speech","C8 nerve hand motor","CN X vagus/heart","20Hz beta waves"]', 'Physiology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-block', '[2,12,18,4]', '["Aspen(02) fear","Gentian(12) doubt","Impatiens(18) time","Centaury(04) subservience"]', 'Bach Flower');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-space', '[5,2,4,6]', '["Center(05) health","Kun(02) relationships","Xun(04) wood/nature","Qian(06) heaven"]', 'Feng Shui');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-time', '[40,10,6,2]', '["Gamma(40Hz)","Alpha(10Hz)","Theta(06Hz)","Delta(02Hz)"]', 'Brain Waves');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-ancestor', '[1,4,2,5]', '["Root(01)","Heart(04)","Sacral(02)","Throat(05)"]', 'Chakras');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('purpose-animal', '[1,15,70,90]', '["bee ~1","lion ~15","elephant ~70","whale ~90"]', 'Zoology');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-light', '[15,80,35,4]', '["Forest 15%","new snow 80%","sand 35%","charcoal 04%"]', 'Albedo (%)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-breath', '[14,32,28,6]', '["Normal 14","stress 32","tachypnea 28","meditative 06"]', 'Respiratory (BPM)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-moment-color', '[6,43,20,9]', '["PW6 titanium white","PY43 yellow ochre","PO20 cadmium orange","PBk9 ivory black"]', 'Pigment Codes');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-body', '[3,47,69,32]', '["GABA(103)","glutamate(147)","norepinephrine(169)","melatonin(232) — molecular weights trimmed"]', 'Biochemistry');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-spaciousness', '[60,30,96,24]', '["French 60\"","standard 30\"","grand entrance 96\"","closet 24\""]', 'Door Widths (in)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-time-feel', '[60,24,30,1]', '["High motion 60fps","cinematic 24fps","broadcast 30fps","timelapse 01fps"]', 'Frame Rates (FPS)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-hands', '[76,65,98,70]', '["Warm comfort 76°","AC cool 65°","heat wave 98°","ambient 70°"]', 'Thermostat (°F)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-feeling', '[9,63,35,10]', '["Gate 09 focus","Gate 63 inquiry","Gate 35 progress","Gate 10 love of self"]', 'Human Design');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-texture', '[10,90,20,70]', '["Talc(1→10)","corundum(9→90)","gypsum(2→20)","quartz(7→70)"]', 'Mohs (×10)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-space-energy', '[1,7,11,12]', '["unison(01)","perfect 5th(07)","major 7th(11)","octave(12)"]', 'Music Intervals');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-surroundings', '[50,99,14,85]', '["Standard eye 50mm","telephoto 99mm","ultra-wide 14mm","portrait 85mm"]', 'Camera Lenses (mm)');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('ground-eyes', '[10,64,4,16]', '["daylight(100→10)","night(6400→64)","action(400→04)","grain(1600→16)"]', 'ISO Sensitivity');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-number', '[9,21,33,66]', '["3×3 = 9 sacred triple","7×3 = 21 fortune","11×3 = 33 master teacher","22×3 = 66 cosmic service"]', 'Triplicities');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-weather', '[1,61,95,45]', '["01 clouds dissolving","61 light rain","95 thunderstorm","45 fog"]', 'WMO/SYNOP Codes');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-animal', '[29,30,23,25]', '["Rooster(2029)","Dog(2030)","Rabbit(2023)","Snake(2025)"]', 'Chinese Zodiac Year');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-direction', '[4,2,1,3]', '["East(1)","South(2)","West(3)","North(4)"]', 'Mahjong');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-door', '[30,50,90,10]', '["Red(3xxx→30)","Blue(5xxx→50)","Black(9xxx→90)","Gold/Yellow(1xxx→10)"]', 'RAL Colors');
INSERT INTO coordinate_mappings (question_id, option_values, option_meanings, source) VALUES ('weird-key', '[5,99,3,1]', '["Rook/Castle(5)","King/Heart(infinite→99)","Bishop/Memory(3)","Pawn/Nothing(1)"]', 'Chess');

-- Total: 126 mappings
